// Auth
export const SET_USER  = 'SET_USER'; 
export const SET_TOKEN = 'SET_TOKEN'; 

// Transactions 
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'; 
export const SET_TRACKED_DATES = 'SET_TRACKED_DATES'; 
export const SET_DATE_FILTERS = 'SET_DATE_FILTERS'; 
export const SET_CATEGORY_FILTERS = 'SET_CATEGORY_FILTERS'; 
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS'; 
export const SET_USER_CATEGORIES = 'SET_USER_CATEGORIES'; 
export const SET_TRANSACTIONS_LOADING = 'SET_TRANSACTIONS_LOADING'; 