// Auth
export const SET_USER  = 'SET_USER'; 
export const SET_TOKEN = 'SET_TOKEN'; 
export const SET_ALL_USERS = 'SET_ALL_USERS';

// Transactions 
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'; 
export const SET_TRACKED_DATES = 'SET_TRACKED_DATES'; 
export const SET_DATE_FILTERS = 'SET_DATE_FILTERS'; 
export const SET_CATEGORY_FILTERS = 'SET_CATEGORY_FILTERS'; 
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS'; 
export const SET_USER_CATEGORIES = 'SET_USER_CATEGORIES'; 
export const SET_TRANSACTIONS_LOADING = 'SET_TRANSACTIONS_LOADING'; 
export const SET_CATEGORIZED_EXPENSES = 'SET_CATEGORIZED_EXPENSES'; 
export const SET_CATEGORIZED_EXPENSES_LOADING = 'SET_CATEGORIZED_EXPENSES_LOADING'; 
export const SET_TOTALS = 'SET_TOTALS'; 

// Annual Transactions 
export const SET_ANNUAL_TOTALS = 'SET_ANNUAL_TOTALS'; 
export const SET_ANNUAL_CATEGORIZED_EXPENSES = 'SET_ANNUAL_CATEGORIZED_EXPENSES'; 
export const SET_ANNUAL_CATEGORIZED_EXPENSES_LOADING = 'SET_ANNUAL_CATEGORIZED_EXPENSES_LOADING'; 

// Roommates 
export const SET_ROOMATE_REQUESTS = 'SET_ROOMATE_REQUESTS'; 
export const SET_ROOMATES = 'SET_ROOMATES'; 
export const SET_ROOMATES_TRANSACTIONS = 'SET_ROOMATES_TRANSACTIONS'; 
export const SET_ROOMATE_TRANS_TO_AND_FROM = 'SET_ROOMATE_TRANS_TO_AND_FROM'; 
export const SET_ROOMMATE_NOTIFICATIONS = 'SET_ROOMMATE_NOTIFICATIONS'; 