# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'budgetspacefinance' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for budgetspacefinance
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'budgetspacefinanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'budgetspacefinance-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for budgetspacefinance-tvOS

  target 'budgetspacefinance-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
